---
apiVersion: anarchy.gpte.redhat.com/v1
kind: AnarchyGovernor
metadata:
  name: gitops
spec:
  ansibleGalaxyRequirements:
    collections: []
    roles:
    - name: k8s_config
      src: git+https://github.com/redhat-gpte-devopsautomation/k8s_config.git
      version: 0.1.4
  runner: default
  vars: {}
  subjectEventHandlers:
    create:
      tasks:
      - name: Schedule configure
        anarchy_schedule_action:
          action: configure
    update:
      tasks:
      - name: Schedule configure
        anarchy_schedule_action:
          action: configure
  actions:
    configure:
      preTasks:
      - name: Get default ingress controller
        register: r_default_ingress_controller
        k8s_facts:
          api_version:  operator.openshift.io/v1
          kind: IngressController
          name: default
          namespace: openshift-ingress-operator
      - name: Set discovered facts
        set_fact:
          openshift_ingress_default_subdomain: >-
            {{ r_default_ingress_controller.resources[0].status.domain }}
      roles:
      - k8s_config
      tasks:
      - name: Schedule next run
        anarchy_schedule_action:
          action: configure
          after: 1h
